Resources:
  Mys3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private | PublicRead | PublicReadWrite | AuthenticatedRead | LogDeliveryWrite | BucketOwnerRead | BucketOwnerFullControl
      BucketName: sidprojectcloudformation
     

Outputs:
  stackbucketname:
    Description: Bucket name of the bucket deployed
    Value: !Ref Mys3Bucket
    Export: 
      Name: Bucket
